<?php

namespace FirstEngineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoAcreditacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoAcreditacionRepository extends EntityRepository
{
}
