<?php

namespace FirstEngineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InduccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InduccionesRepository extends EntityRepository
{
}
