<?php

namespace FirstEngineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonasRepository extends EntityRepository
{
}
