<?php

namespace FirstEngineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroPasesVehiculosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroPasesVehiculosRepository extends EntityRepository
{
}
