<?php

namespace FirstEngineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegistroDocsVehiculosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroDocsVehiculosRepository extends EntityRepository
{
}
